import type { Term } from '../types';

export const seedTerms: Term[] = [
  {
    id: 'ds-array',
    name: '배열',
    englishName: 'Array',
    category: 'data-structure',
    definition: '동일한 자료형의 데이터를 연속된 메모리 공간에 저장하는 선형 자료구조. 인덱스로 임의 접근이 가능하다.',
    complexity: '접근 O(1), 삽입/삭제 O(n)',
    keywords: ['인덱스', '연속 메모리', '고정 크기', '임의 접근'],
    example: 'const arr = [1, 2, 3];\narr[0]; // O(1)',
    related: ['ds-linked-list'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-linked-list',
    name: '연결 리스트',
    englishName: 'Linked List',
    category: 'data-structure',
    definition: '각 노드가 데이터와 다음 노드의 참조를 가지는 선형 자료구조. 동적 크기 조절이 가능하다.',
    complexity: '접근 O(n), 삽입/삭제 O(1)',
    keywords: ['노드', '포인터', '동적 크기'],
    example: 'class Node {\n  value: number;\n  next: Node | null;\n}',
    related: ['ds-array', 'ds-stack'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-stack',
    name: '스택',
    englishName: 'Stack',
    category: 'data-structure',
    definition: '후입선출(LIFO) 원칙을 따르는 선형 자료구조. 가장 마지막에 삽입된 요소가 먼저 제거된다.',
    complexity: 'push/pop/peek O(1)',
    keywords: ['LIFO', 'push', 'pop', '함수 호출 스택'],
    example: 'const stack = [];\nstack.push(1);\nstack.pop();',
    related: ['ds-queue'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-queue',
    name: '큐',
    englishName: 'Queue',
    category: 'data-structure',
    definition: '선입선출(FIFO) 원칙을 따르는 선형 자료구조. 가장 먼저 삽입된 요소가 먼저 제거된다.',
    complexity: 'enqueue/dequeue O(1)',
    keywords: ['FIFO', 'enqueue', 'dequeue', 'BFS'],
    example: 'const queue = [];\nqueue.push(1);\nqueue.shift();',
    related: ['ds-stack', 'ds-priority-queue'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-hash-table',
    name: '해시 테이블',
    englishName: 'Hash Table',
    category: 'data-structure',
    definition: '키를 해시 함수로 변환해 인덱스로 사용하는 자료구조. 평균적으로 매우 빠른 검색을 제공한다.',
    complexity: '평균 O(1), 최악 O(n)',
    keywords: ['해시 함수', '충돌', '체이닝', '개방 주소법'],
    example: 'const map = new Map();\nmap.set("a", 1);\nmap.get("a");',
    related: ['ds-array'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-binary-tree',
    name: '이진 트리',
    englishName: 'Binary Tree',
    category: 'data-structure',
    definition: '각 노드가 최대 두 개의 자식 노드를 가지는 트리 자료구조.',
    complexity: '순회 O(n)',
    keywords: ['루트', '리프', '깊이', '높이'],
    example: 'class TreeNode {\n  value: number;\n  left: TreeNode | null;\n  right: TreeNode | null;\n}',
    related: ['ds-bst', 'ds-heap'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-bst',
    name: '이진 탐색 트리',
    englishName: 'Binary Search Tree',
    category: 'data-structure',
    definition: '왼쪽 자식은 부모보다 작고, 오른쪽 자식은 부모보다 큰 정렬된 이진 트리.',
    complexity: '평균 O(log n), 최악 O(n)',
    keywords: ['BST', '정렬', '균형', 'AVL'],
    example: '// 왼쪽 < 부모 < 오른쪽',
    related: ['ds-binary-tree'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-heap',
    name: '힙',
    englishName: 'Heap',
    category: 'data-structure',
    definition: '부모 노드가 자식보다 항상 크거나(최대힙) 작은(최소힙) 완전 이진 트리.',
    complexity: '삽입/삭제 O(log n), 최댓값 조회 O(1)',
    keywords: ['최대힙', '최소힙', '우선순위 큐', '완전 이진 트리'],
    example: '// 부모 ≥ 자식 (최대힙)',
    related: ['ds-binary-tree', 'ds-priority-queue'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-graph',
    name: '그래프',
    englishName: 'Graph',
    category: 'data-structure',
    definition: '정점(vertex)과 간선(edge)으로 이루어진 비선형 자료구조. 방향/무방향, 가중/비가중으로 분류된다.',
    complexity: '인접 리스트 공간 O(V+E)',
    keywords: ['정점', '간선', '인접 리스트', '인접 행렬', 'BFS', 'DFS'],
    example: 'const graph = {\n  A: ["B", "C"],\n  B: ["A"]\n};',
    related: ['ds-binary-tree'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-trie',
    name: '트라이',
    englishName: 'Trie',
    category: 'data-structure',
    definition: '문자열의 각 문자를 노드로 저장하는 트리. 자동완성·사전 검색에 사용된다.',
    complexity: '검색/삽입 O(m), m은 문자열 길이',
    keywords: ['접두사 트리', '자동완성', '사전'],
    example: '// "apple" → a → p → p → l → e',
    related: ['ds-binary-tree'],
    createdAt: Date.now(),
  },
];