import type { Term } from '../types';

export const seedTerms: Term[] = [
  {
    id: 'ds-array',
    name: '배열',
    englishName: 'Array',
    category: 'data-structure',
    definition: '동일한 자료형의 데이터를 연속된 메모리 공간에 저장하는 선형 자료구조. 인덱스로 임의 접근이 가능하다.',
    complexity: '접근 O(1), 삽입/삭제 O(n)',
    keywords: ['인덱스', '연속 메모리', '고정 크기', '임의 접근'],
    example: 'const arr = [1, 2, 3];\narr[0]; // O(1)',
    related: ['ds-linked-list'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-linked-list',
    name: '연결 리스트',
    englishName: 'Linked List',
    category: 'data-structure',
    definition: '각 노드가 데이터와 다음 노드의 참조를 가지는 선형 자료구조. 동적 크기 조절이 가능하다.',
    complexity: '접근 O(n), 삽입/삭제 O(1)',
    keywords: ['노드', '포인터', '동적 크기'],
    example: 'class Node {\n  value: number;\n  next: Node | null;\n}',
    related: ['ds-array', 'ds-stack'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-stack',
    name: '스택',
    englishName: 'Stack',
    category: 'data-structure',
    definition: '후입선출(LIFO) 원칙을 따르는 선형 자료구조. 가장 마지막에 삽입된 요소가 먼저 제거된다.',
    complexity: 'push/pop/peek O(1)',
    keywords: ['LIFO', 'push', 'pop', '함수 호출 스택'],
    example: 'const stack = [];\nstack.push(1);\nstack.pop();',
    related: ['ds-queue'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-queue',
    name: '큐',
    englishName: 'Queue',
    category: 'data-structure',
    definition: '선입선출(FIFO) 원칙을 따르는 선형 자료구조. 가장 먼저 삽입된 요소가 먼저 제거된다.',
    complexity: 'enqueue/dequeue O(1)',
    keywords: ['FIFO', 'enqueue', 'dequeue', 'BFS'],
    example: 'const queue = [];\nqueue.push(1);\nqueue.shift();',
    related: ['ds-stack', 'ds-priority-queue'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-hash-table',
    name: '해시 테이블',
    englishName: 'Hash Table',
    category: 'data-structure',
    definition: '키를 해시 함수로 변환해 인덱스로 사용하는 자료구조. 평균적으로 매우 빠른 검색을 제공한다.',
    complexity: '평균 O(1), 최악 O(n)',
    keywords: ['해시 함수', '충돌', '체이닝', '개방 주소법'],
    example: 'const map = new Map();\nmap.set("a", 1);\nmap.get("a");',
    related: ['ds-array'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-binary-tree',
    name: '이진 트리',
    englishName: 'Binary Tree',
    category: 'data-structure',
    definition: '각 노드가 최대 두 개의 자식 노드를 가지는 트리 자료구조.',
    complexity: '순회 O(n)',
    keywords: ['루트', '리프', '깊이', '높이'],
    example: 'class TreeNode {\n  value: number;\n  left: TreeNode | null;\n  right: TreeNode | null;\n}',
    related: ['ds-bst', 'ds-heap'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-bst',
    name: '이진 탐색 트리',
    englishName: 'Binary Search Tree',
    category: 'data-structure',
    definition: '왼쪽 자식은 부모보다 작고, 오른쪽 자식은 부모보다 큰 정렬된 이진 트리.',
    complexity: '평균 O(log n), 최악 O(n)',
    keywords: ['BST', '정렬', '균형', 'AVL'],
    example: '// 왼쪽 < 부모 < 오른쪽',
    related: ['ds-binary-tree'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-heap',
    name: '힙',
    englishName: 'Heap',
    category: 'data-structure',
    definition: '부모 노드가 자식보다 항상 크거나(최대힙) 작은(최소힙) 완전 이진 트리.',
    complexity: '삽입/삭제 O(log n), 최댓값 조회 O(1)',
    keywords: ['최대힙', '최소힙', '우선순위 큐', '완전 이진 트리'],
    example: '// 부모 ≥ 자식 (최대힙)',
    related: ['ds-binary-tree', 'ds-priority-queue'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-graph',
    name: '그래프',
    englishName: 'Graph',
    category: 'data-structure',
    definition: '정점(vertex)과 간선(edge)으로 이루어진 비선형 자료구조. 방향/무방향, 가중/비가중으로 분류된다.',
    complexity: '인접 리스트 공간 O(V+E)',
    keywords: ['정점', '간선', '인접 리스트', '인접 행렬', 'BFS', 'DFS'],
    example: 'const graph = {\n  A: ["B", "C"],\n  B: ["A"]\n};',
    related: ['ds-binary-tree'],
    createdAt: Date.now(),
  },
  {
    id: 'ds-trie',
    name: '트라이',
    englishName: 'Trie',
    category: 'data-structure',
    definition: '문자열의 각 문자를 노드로 저장하는 트리. 자동완성·사전 검색에 사용된다.',
    complexity: '검색/삽입 O(m), m은 문자열 길이',
    keywords: ['접두사 트리', '자동완성', '사전'],
    example: '// "apple" → a → p → p → l → e',
    related: ['ds-binary-tree'],
    createdAt: Date.now(),
  },
  {
    id: 'algo-bubble-sort',
    name: '버블 정렬',
    englishName: 'Bubble Sort',
    category: 'algorithm',
    definition: '인접한 두 원소를 비교해 큰 값을 뒤로 보내는 과정을 반복하는 정렬 알고리즘.',
    complexity: '평균/최악 O(n²), 최선 O(n)',
    keywords: ['비교 정렬', '안정 정렬', '제자리 정렬'],
    example: 'for (let i = 0; i < n; i++)\n  for (let j = 0; j < n - i - 1; j++)\n    if (a[j] > a[j+1]) swap(a, j, j+1);',
    related: ['algo-quick-sort'],
    createdAt: Date.now(),
  },
  {
    id: 'algo-quick-sort',
    name: '퀵 정렬',
    englishName: 'Quick Sort',
    category: 'algorithm',
    definition: '피벗을 기준으로 작은 값과 큰 값을 분할 후 재귀적으로 정렬하는 분할 정복 알고리즘.',
    complexity: '평균 O(n log n), 최악 O(n²)',
    keywords: ['분할 정복', '피벗', '재귀'],
    example: '// 피벗 선택 → 분할 → 재귀',
    related: ['algo-bubble-sort'],
    createdAt: Date.now(),
  },
  {
    id: 'algo-binary-search',
    name: '이진 탐색',
    englishName: 'Binary Search',
    category: 'algorithm',
    definition: '정렬된 배열에서 탐색 범위를 절반씩 줄여가며 값을 찾는 알고리즘.',
    complexity: 'O(log n)',
    keywords: ['정렬 필수', '분할 정복', '로그 시간'],
    example: 'while (lo <= hi) {\n  const mid = (lo + hi) >> 1;\n  if (a[mid] === target) return mid;\n}',
    related: ['ds-bst'],
    createdAt: Date.now(),
  },
  {
    id: 'algo-dfs',
    name: '깊이 우선 탐색',
    englishName: 'Depth-First Search',
    category: 'algorithm',
    definition: '한 경로를 끝까지 탐색한 뒤 되돌아오는 그래프/트리 순회 알고리즘. 스택 또는 재귀로 구현한다.',
    complexity: 'O(V + E)',
    keywords: ['DFS', '재귀', '스택', '백트래킹'],
    example: 'function dfs(node) {\n  visited.add(node);\n  for (const n of adj[node])\n    if (!visited.has(n)) dfs(n);\n}',
    related: ['algo-bfs', 'ds-graph', 'ds-stack'],
    createdAt: Date.now(),
  },
  {
    id: 'algo-bfs',
    name: '너비 우선 탐색',
    englishName: 'Breadth-First Search',
    category: 'algorithm',
    definition: '시작 노드에서 가까운 노드부터 차례로 탐색하는 그래프/트리 순회 알고리즘. 큐를 사용한다.',
    complexity: 'O(V + E)',
    keywords: ['BFS', '큐', '최단 경로'],
    example: 'const queue = [start];\nwhile (queue.length) {\n  const node = queue.shift();\n  // ...\n}',
    related: ['algo-dfs', 'ds-graph', 'ds-queue'],
    createdAt: Date.now(),
  },
  {
    id: 'net-tcp-ip',
    name: 'TCP/IP',
    englishName: 'TCP/IP',
    category: 'network',
    definition: '인터넷에서 데이터 전송을 담당하는 핵심 프로토콜 모음. TCP는 신뢰성 있는 연결, IP는 패킷 라우팅을 담당한다.',
    complexity: '4계층 모델',
    keywords: ['신뢰성', '연결 지향', '패킷', '재전송'],
    example: '// 웹·이메일·파일 전송의 기반',
    related: ['net-http', 'net-handshake'],
    createdAt: Date.now(),
  },
  {
    id: 'net-http',
    name: 'HTTP / HTTPS',
    englishName: 'HyperText Transfer Protocol',
    category: 'network',
    definition: '웹에서 클라이언트와 서버가 데이터를 주고받는 응용 계층 프로토콜. HTTPS는 TLS로 암호화한 안전한 버전이다.',
    complexity: '응용 계층',
    keywords: ['요청/응답', 'GET', 'POST', 'TLS', '상태비저장'],
    example: 'GET /index.html HTTP/1.1\nHost: example.com',
    related: ['net-tcp-ip', 'net-dns'],
    createdAt: Date.now(),
  },
  {
    id: 'net-osi',
    name: 'OSI 7계층',
    englishName: 'OSI 7 Layers',
    category: 'network',
    definition: '네트워크 통신을 7개 계층(물리·데이터링크·네트워크·전송·세션·표현·응용)으로 추상화한 국제 표준 모델.',
    complexity: '7계층 모델',
    keywords: ['추상화', '계층 모델', '표준', 'ISO'],
    example: '// 응용 > 표현 > 세션 > 전송 > 네트워크 > 데이터링크 > 물리',
    related: ['net-tcp-ip'],
    createdAt: Date.now(),
  },
  {
    id: 'net-dns',
    name: 'DNS',
    englishName: 'Domain Name System',
    category: 'network',
    definition: '도메인 이름(example.com)을 IP 주소로 변환하는 분산 디렉터리 시스템. 인터넷의 전화번호부 역할을 한다.',
    complexity: '계층적 분산 구조',
    keywords: ['도메인', '이름 해석', '캐싱', '재귀 질의'],
    example: 'example.com → 93.184.216.34',
    related: ['net-http'],
    createdAt: Date.now(),
  },
  {
    id: 'net-handshake',
    name: '3-way Handshake',
    englishName: '3-way Handshake',
    category: 'network',
    definition: 'TCP 연결을 설정하기 위해 클라이언트와 서버가 SYN → SYN-ACK → ACK 세 번의 패킷을 교환하는 절차.',
    complexity: 'TCP 연결 수립',
    keywords: ['SYN', 'ACK', '연결 수립', '신뢰성'],
    example: 'C → S: SYN\nS → C: SYN-ACK\nC → S: ACK',
    related: ['net-tcp-ip'],
    createdAt: Date.now(),
  },
  {
    id: 'db-normalization',
    name: '정규화',
    englishName: 'Normalization',
    category: 'database',
    definition: '데이터 중복을 줄이고 무결성을 높이기 위해 테이블을 작은 단위로 분해하는 과정. 1NF, 2NF, 3NF, BCNF 등의 단계가 있다.',
    complexity: '1NF ~ BCNF',
    keywords: ['1NF', '2NF', '3NF', '함수적 종속', '무결성'],
    example: '// 중복 제거 → 이상 현상(anomaly) 방지',
    related: ['db-join'],
    createdAt: Date.now(),
  },
  {
    id: 'db-acid',
    name: 'ACID',
    englishName: 'ACID',
    category: 'database',
    definition: '트랜잭션이 안전하게 수행되기 위한 네 가지 속성: 원자성(Atomicity), 일관성(Consistency), 격리성(Isolation), 지속성(Durability).',
    complexity: '트랜잭션 보장 속성',
    keywords: ['원자성', '일관성', '격리성', '지속성'],
    example: '// 송금: 출금+입금이 모두 성공 or 모두 실패',
    related: ['db-transaction'],
    createdAt: Date.now(),
  },
  {
    id: 'db-index',
    name: '인덱스',
    englishName: 'Index',
    category: 'database',
    definition: '테이블의 검색 속도를 향상시키기 위한 자료구조. 주로 B-Tree나 해시를 사용하며, 추가 저장공간과 쓰기 오버헤드를 대가로 한다.',
    complexity: '검색 O(log n)',
    keywords: ['B-Tree', '해시', '검색 성능', '쓰기 오버헤드'],
    example: 'CREATE INDEX idx_email ON users(email);',
    related: ['ds-bst', 'ds-hash-table'],
    createdAt: Date.now(),
  },
  {
    id: 'db-join',
    name: 'JOIN',
    englishName: 'JOIN',
    category: 'database',
    definition: '두 개 이상의 테이블을 특정 조건으로 결합해 새로운 결과 집합을 만드는 연산. INNER, LEFT, RIGHT, FULL OUTER 등이 있다.',
    complexity: '연산 종류에 따라 다름',
    keywords: ['INNER JOIN', 'LEFT JOIN', '관계형', '외래키'],
    example: 'SELECT * FROM a\nINNER JOIN b ON a.id = b.a_id;',
    related: ['db-normalization'],
    createdAt: Date.now(),
  },
  {
    id: 'db-transaction',
    name: '트랜잭션',
    englishName: 'Transaction',
    category: 'database',
    definition: '하나의 논리적 작업 단위로 묶인 데이터베이스 연산들의 집합. COMMIT으로 확정하거나 ROLLBACK으로 취소한다.',
    complexity: 'ACID 보장',
    keywords: ['COMMIT', 'ROLLBACK', '원자성', '동시성'],
    example: 'BEGIN;\nUPDATE ...;\nCOMMIT;',
    related: ['db-acid'],
    createdAt: Date.now(),
  },
  {
    id: 'os-process-thread',
    name: '프로세스와 스레드',
    englishName: 'Process vs Thread',
    category: 'os',
    definition: '프로세스는 독립된 메모리 공간을 가진 실행 단위, 스레드는 프로세스 내에서 자원을 공유하는 더 작은 실행 단위.',
    complexity: '자원 격리 vs 공유',
    keywords: ['PCB', '주소공간', '경량 프로세스', '컨텍스트'],
    example: '// 프로세스: Chrome 탭 / 스레드: 탭 내 렌더링 작업',
    related: ['os-context-switching', 'os-mutex'],
    createdAt: Date.now(),
  },
  {
    id: 'os-context-switching',
    name: '컨텍스트 스위칭',
    englishName: 'Context Switching',
    category: 'os',
    definition: 'CPU가 실행 중인 프로세스/스레드를 다른 것으로 전환할 때, 현재 상태를 저장하고 다음 작업의 상태를 복원하는 과정.',
    complexity: '오버헤드 발생',
    keywords: ['PCB', '레지스터 저장', '오버헤드', '스케줄링'],
    example: '// 너무 잦으면 CPU 시간 대부분이 스위칭에 소모됨',
    related: ['os-process-thread'],
    createdAt: Date.now(),
  },
  {
    id: 'os-deadlock',
    name: '데드락',
    englishName: 'Deadlock',
    category: 'os',
    definition: '둘 이상의 프로세스가 서로 상대방이 가진 자원을 기다리며 영원히 진행되지 못하는 교착 상태.',
    complexity: '4가지 조건 동시 충족 시 발생',
    keywords: ['상호배제', '점유와 대기', '비선점', '순환 대기'],
    example: '// A: 자원1 점유, 자원2 대기\n// B: 자원2 점유, 자원1 대기',
    related: ['os-mutex'],
    createdAt: Date.now(),
  },
  {
    id: 'os-paging',
    name: '페이징',
    englishName: 'Paging',
    category: 'os',
    definition: '가상 메모리를 고정 크기 페이지로 나누어 물리 메모리의 프레임에 매핑하는 메모리 관리 기법. 외부 단편화를 제거한다.',
    complexity: '내부 단편화 발생',
    keywords: ['가상 메모리', '페이지 테이블', 'TLB', '단편화'],
    example: '// 4KB 페이지 → 물리 프레임에 매핑',
    related: [],
    createdAt: Date.now(),
  },
  {
    id: 'os-mutex',
    name: '뮤텍스와 세마포어',
    englishName: 'Mutex & Semaphore',
    category: 'os',
    definition: '동시성 제어 기법. 뮤텍스는 1개의 자원에 대한 상호배제(잠금), 세마포어는 N개의 자원에 대한 카운터 기반 제어를 한다.',
    complexity: '동시성 제어',
    keywords: ['상호배제', 'lock', 'P/V 연산', '임계영역'],
    example: 'mutex.lock();\n// 임계 영역\nmutex.unlock();',
    related: ['os-deadlock', 'os-process-thread'],
    createdAt: Date.now(),
  },
  {
    id: 'pattern-singleton',
    name: '싱글톤 패턴',
    englishName: 'Singleton Pattern',
    category: 'design-pattern',
    definition: '클래스의 인스턴스가 프로그램 전체에서 단 하나만 존재하도록 보장하는 생성 패턴. 전역 접근점을 제공한다.',
    complexity: '생성 패턴 (Creational)',
    keywords: ['단일 인스턴스', '전역 접근', '게으른 초기화', 'GoF'],
    example: 'class Logger {\n  static instance: Logger;\n  static getInstance() { ... }\n}',
    related: ['pattern-factory'],
    createdAt: Date.now(),
  },
  {
    id: 'pattern-observer',
    name: '옵저버 패턴',
    englishName: 'Observer Pattern',
    category: 'design-pattern',
    definition: '한 객체의 상태가 변할 때 의존하는 객체들(옵저버)에게 자동으로 알리는 행동 패턴. 발행-구독 모델의 기반이다.',
    complexity: '행동 패턴 (Behavioral)',
    keywords: ['Publisher', 'Subscriber', '이벤트', '의존성 역전'],
    example: 'subject.subscribe(observer);\nsubject.notify();',
    related: ['pattern-mvc'],
    createdAt: Date.now(),
  },
  {
    id: 'pattern-factory',
    name: '팩토리 패턴',
    englishName: 'Factory Pattern',
    category: 'design-pattern',
    definition: '객체 생성 로직을 별도 메서드/클래스로 분리해, 클라이언트가 구체 클래스를 직접 알지 않아도 객체를 만들 수 있게 하는 생성 패턴.',
    complexity: '생성 패턴 (Creational)',
    keywords: ['추상화', '느슨한 결합', 'new 캡슐화', '확장성'],
    example: 'class CarFactory {\n  static create(type) {\n    if (type === "sedan") return new Sedan();\n  }\n}',
    related: ['pattern-singleton'],
    createdAt: Date.now(),
  },
  {
    id: 'pattern-strategy',
    name: '전략 패턴',
    englishName: 'Strategy Pattern',
    category: 'design-pattern',
    definition: '알고리즘 군을 캡슐화하고 상호 교환 가능하게 만들어, 클라이언트가 런타임에 알고리즘을 선택할 수 있게 하는 행동 패턴.',
    complexity: '행동 패턴 (Behavioral)',
    keywords: ['알고리즘 캡슐화', '런타임 교체', '다형성', 'OCP'],
    example: 'context.setStrategy(new QuickSort());\ncontext.sort(arr);',
    related: ['algo-quick-sort', 'algo-bubble-sort'],
    createdAt: Date.now(),
  },
  {
    id: 'pattern-mvc',
    name: 'MVC 패턴',
    englishName: 'Model-View-Controller',
    category: 'design-pattern',
    definition: '애플리케이션을 Model(데이터), View(화면), Controller(입력 처리)로 분리하는 아키텍처 패턴. 관심사 분리의 대표 사례.',
    complexity: '아키텍처 패턴',
    keywords: ['관심사 분리', 'Model', 'View', 'Controller'],
    example: '// React: Model=state, View=JSX, Controller=event handlers',
    related: ['pattern-observer'],
    createdAt: Date.now(),
  },
];